# Generated by Django 3.2.6 on 2021-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images/music'),
        ),
    ]
